services:
  - type: worker
    name: telebot-scheduler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: TZ
        value: Asia/Seoul
