services:
  - type: worker
    name: telebot-scheduler
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: UPSTASH_REDIS_URL
        sync: false
      - key: UPSTASH_REDIS_TOKEN
        sync: false
      - key: TZ
        value: Asia/Seoul
